[theme]
primaryColor = "#FF4B4B"          # Button and highlight color (red-pink)
backgroundColor = "#FFFFFF"        # Main background (white)
secondaryBackgroundColor = "#F0F2F6"  # Sidebar background (light gray)
textColor = "#262730"              # Main text color (almost black)
font = "Poppins"                   # Sleek modern font

[server]
headless = true
port = $PORT
enableCORS = false
